title:            "title"
url:              http://rafaelsw.com
permalink:        pretty
highlighter:      pygments
markdown:         kramdown
google_analytics:
timezone:         Europe/London
paginate: 5
gems:
  - jemoji
  - jekyll-mentions
